### ISSUE TITLE
Options for automatic pairs file generation

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/q2-autopepsirf#15]
Currently, the diffEnrich pipeline in q2-autopepsirf, by default, implements the --inferPairs option from the original autoPepSIRF python wrapper, AND this is the only option the user currently has for automatic generation of a pairs file for the enrich module. 

We would like to add two additional options for the automatic generation of a pairs file AND allow the user to specify which option to use. Here is a description of the options:

1. inferPairs (current implementation)
2. flexibleReps - will infer the number of replicates for each sample based on sample names, and will not require any specific number of replicates for inclusion. Therefore, some samples may have a single replicate, some may have 2, 3, 4 etc. And all replicates of a given sample will be considered for determining enriched peptides. 
3. sEnrich - All samples will be processed individually as samples with only one replicate
4. userDefined - For the user to provide an input file that explicitly states when samples should be treated as replicates. In this case, the pipeline does not need to generate such a file on the fly, it will be user provided.

**Comment by Annabelle-Brown** [comment]
I have encountered an issue with the sEnrich option. When the replicates are handled individually as a single replicate, the colsum repscatters graph fails because it needs two replicates to create a graph. How would you suggest fixing this error?

**Comment by jtladner** [comment]
Makes sense. Ideally we would simply not generate the rep scatters with this option, but I'm guessing this isn't an option with Qiime, right?

Could repscatters be modified to be able to simply use the same replicate on both the x and y axes, if only one replicate is provided?

**Comment by Annabelle-Brown** [comment]
Correct, it isn't an option to not generate rep scatter currently with Qiime2. I could look into generating it with the same replicate on both the x and y axes.
