### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/q2-autopepsirf#20]
Command: qiime autopepsirf diffEnrich  --i-raw-data using_PV1.7_40nt-Uq.qza  --p-negative-id SB_ --i-negative-control  /Volumes/GoogleDrive/Shared\ drives/LadnerLab/Support/bins/PV1/PV1.7_pGpA/NH_pAx4_pGx7/PV1.7_pAx4pGx7_SBs_40nt-Uq_CS.qza   --i-bins /Volumes/GoogleDrive/Shared\ drives/LadnerLab/Support/bins/PV1/PV1.7_pGpA/NH_pAx4_pGx7/PV1.7_pAx4_pGx7_min300r1_bins.qza   --p-exact-z-thresh 10  --p-exact-cs-thresh 2  --p-pepsirf-tsv-dir aps-diffEnrich_z10_cs2-tsv  --p-tsv-base-str using_PV1.7_40nt-Uq  --p-pepsirf-binary pepsirf  --output-dir aps-diffEnrich_z10_cs2-qz --verbose >aps_z10_cs2.out

Working directory: LadnerLab/Manuscripts/NH-PepSeq/Analysis/PV1/PV1.7/NHbins/pAx4_pGx7

Error:
![Screen Shot](https://user-images.githubusercontent.com/10342801/157273398-6098e22c-c3ac-4d61-a3eb-5357c95adf61.png)

**Comment by Annabelle-Brown** [comment]
The issue has been resolved on q2-ps-plot.
